### PR TITLE
Add test for the shipped widgets + fixes

### PR DESCRIPTION
**Pull request by sergei-maertens**
I've noticed that there are some changes in ``sniplates/django.html`` needed (see also https://github.com/funkybob/django-sniplates/issues/36).

This initial PR adds tests for the default widgets with the correct expected output. The following commits will fix the failing test(s).

### CODE REVIEW

**Comment by sergei-maertens** [comment]
I've fixed the widgets so far - all environments are passing with ``tox`` locally.

There should be some tests added with a bound form and initial data, but I think I've covered a big deal already.

**Comment by sergei-maertens** [comment]
I noticed that the Travis setup doesn't use Tox, is there a particular reason? Would be nice to keep the testing config in one place as much as possible, and I'd vote for Tox for that:

* it runs `setup.py install`, so any packacking errors turn up
* easy to run locally to check if you broke any versions
* easy Travis integration: https://github.com/bigjason/django-choices/blob/master/.travis.yml#L11

Would like to hear opinions :-)

**Comment by funkybob** [comment]
@schinckel  added the tox.ini ... I never used it.

It's not hard to go either way -- add the features you suggest, or wrap around tox.

**Comment by sergei-maertens** [comment]
Yeah, I didn't do it yet, in case there was a though out reason and it would pollute this PR. I'll have a new PR with the Travis infrastructure wrapped around tox during this week.

I'll also add coverage tracking to the mix, since that's not set up yet :)

**Comment by funkybob** [comment]
The same conversion was done for django-classy-settings ... so it's not a difficult process, from what I've seen.

**Comment by sergei-maertens** [comment]
No, exactly, it's a bit of rinse-and-repeat for reusable apps, nothing exciting.

**Pull request merged**
