### PR TITLE
Add support for Django 1.8

### PR DESCRIPTION
**Pull request by fotcorn**
This a a rather silly hack to make tests at least execute on Django 1.8. Most of them still fail because of the heavy template related changes in 1.8.

### CODE REVIEW

**Comment by fotcorn** [comment]
I've just seen julians approach in formulation which is probably a better solution: https://github.com/julianwachholz/formulation/commit/c8d49a205cb475ee1b12b68d437f3eddefa81ff5

**Comment by fotcorn** [comment]
I've stolen @julianwachholz version and updated the pull request.

**Comment by fotcorn** [comment]
A simple workaround fixes all tests on Django 1.8!

**Comment by funkybob** [comment]
Thanks for this, but I actually just pushed my own solution :)

**Pull request closed without merging**
