### PR TITLE
More tests for the default widgets: ClearableFileInput

### PR DESCRIPTION
**Pull request by sergei-maertens**
This adds a test and a fix for the ClearableFileInput widget.

It should increase coverage of the FileInput exploder.

### CODE REVIEW

**Comment by sergei-maertens** [comment]
I will fix the failing tests when I have a bit more time

**Comment by funkybob** [comment]
Would be nice if we could use the django template extension for coverage...

**Comment by sergei-maertens** [comment]
I have no idea if/that it exists, will look it up

**Comment by sergei-maertens** [comment]
I have added the DTL template checker. It's still a bit iffy in places and very strict (complaining about blank lines for instance), but at least we can see what important lines are missed. It drops the total coverage considerably, but I wouldn't worry too much about that 'magic number' in itself.

The template coverage thing also doesn't work for Django 1.9 and pypy*, but it's not crashing in any horrible ways, so imho we can leave it as is and sort it out later.

**Comment by funkybob** [comment]
Is this considered ready for merging now?

**Comment by sergei-maertens** [comment]
For me it is I think, if you find it sufficient. The template coverage is a
bit WIP, but it doesn't cause horrible crashes.

Your call!

**Pull request merged**
